# Generated by Django 4.0.2 on 2022-02-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feliz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
