# Generated by Django 4.0.2 on 2022-02-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feliz', '0004_alter_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
