# Generated by Django 4.0.1 on 2022-02-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feliz', '0008_alter_sell_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
